version: '3.8'

name: animal_app

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: animal_api
    ports:
      - "5076:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./Backend/media:/app/media
      - ./Backend/camunda_challenge_dev.db:/app/camunda_challenge_dev.db
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: animal_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
